/* =============================================================================
   AIOS · AI BASIC KNOWLEDGE 101  —  hand-written, teaching-ready glossary.
   A curated study set of the fundamentals every AI maker / teacher should know.
   Shown in the LIBRARY as the category "AI Basic Knowledge 101".
============================================================================= */
window.AIOS_BASICS = {
  items: [
    /* ---- A. The plumbing: programming & web basics ---- */
    { n: 1, type: "AI Basic Knowledge 101", source: "Basics · Web", title: "01 · API — Application Programming Interface",
      summary: "A way for two programs to talk to each other. One side sends a request, the other sends back a response, in an agreed format. Almost every AI tool is used through an API: you send text in, you get an answer back.",
      why: "When people say \"call the OpenAI API\" or \"the Claude API\", they mean a program is asking the AI a question over the internet.",
      teacher: "Think of a waiter in a restaurant: you don't go into the kitchen — you give your order to the waiter, and the food comes back. The API is the waiter." },
    { n: 2, type: "AI Basic Knowledge 101", source: "Basics · Web", title: "02 · SDK — Software Development Kit",
      summary: "A ready-made toolkit (code + tools) a company gives you so you can build on their service in a few lines, instead of writing everything from scratch.",
      why: "You'll often \"install the OpenAI SDK\" or \"Anthropic SDK\" to add AI to an app quickly.",
      teacher: "If the API is the socket in the wall, the SDK is the appliance with the plug already wired to fit it." },
    { n: 3, type: "AI Basic Knowledge 101", source: "Basics · Web", title: "03 · Gateway (API Gateway)",
      summary: "A single \"front door\" that sits in front of many services. Every request goes through it; it checks who you are, controls traffic and cost, and routes you to the right place.",
      why: "Companies put AI behind a gateway to manage security, billing, and rate limits in one spot.",
      teacher: "Like the reception desk of a big building: everyone enters there, gets checked, and is sent to the right room." },
    { n: 4, type: "AI Basic Knowledge 101", source: "Basics · Web", title: "04 · Endpoint",
      summary: "One specific web address (URL) you send a request to for one job — for example a \"/chat\" endpoint for chatting, or a \"/images\" endpoint for pictures.",
      why: "An API usually has several endpoints, one per task.",
      teacher: "Endpoints are the different counters at a post office — one for stamps, one for parcels." },
    { n: 5, type: "AI Basic Knowledge 101", source: "Basics · Web", title: "05 · Webhook",
      summary: "The reverse of asking. Instead of you asking again and again \"is it ready?\", the service automatically calls YOU the moment something happens.",
      why: "Used to get instant updates — e.g. \"tell my app when the AI finishes the job.\"",
      teacher: "Don't keep checking the oven — let the oven ring you when the cake is done. That ring is a webhook." },
    { n: 6, type: "AI Basic Knowledge 101", source: "Basics · Web", title: "06 · JSON",
      summary: "A simple text format for data, written with { } and \"labels\": values. It is how programs and AIs exchange structured information.",
      why: "Almost all API requests and answers are JSON.",
      teacher: "It's a tidy form with labelled boxes, so both the human and the computer always know which value is which." },
    { n: 7, type: "AI Basic Knowledge 101", source: "Basics · Web", title: "07 · HTTP / REST",
      summary: "The common rules of the web. HTTP is how browsers and servers talk; REST is a tidy style for building APIs on top of it (GET to read, POST to send).",
      why: "When you see \"POST request\" or \"REST API\", this is what they mean.",
      teacher: "HTTP is the postal system; REST is good handwriting on the envelope so the letter gets delivered." },
    { n: 8, type: "AI Basic Knowledge 101", source: "Basics · Web", title: "08 · CLI — Command-Line Interface",
      summary: "Controlling a program by typing text commands in a terminal (for example: claude -p \"summarise this\"), instead of clicking buttons.",
      why: "Most developer AI tools (Claude Code, Codex) run in the CLI.",
      teacher: "Instead of pointing and clicking, you tell the computer exactly what to do in words." },
    { n: 9, type: "AI Basic Knowledge 101", source: "Basics · Web", title: "09 · Library / Package",
      summary: "A bundle of pre-written code you \"install\" and reuse instead of rewriting it. Installed with tools like npm or pip.",
      why: "You stand on others' work — import a library, get the feature for free.",
      teacher: "Like buying ready-made sauce instead of growing the tomatoes yourself." },
    { n: 10, type: "AI Basic Knowledge 101", source: "Basics · Web", title: "10 · Framework",
      summary: "A bigger skeleton you build your whole app inside (React, Next.js). A library is a tool you call when you want; a framework runs the show and calls your code.",
      why: "Choosing a framework shapes how the whole project is built.",
      teacher: "A library is a power drill you pick up; a framework is the pre-built house frame you finish inside." },
    { n: 11, type: "AI Basic Knowledge 101", source: "Basics · Web", title: "11 · Frontend / Backend",
      summary: "Frontend = what the user sees and clicks (the screen). Backend = the hidden server doing the work and holding the data.",
      why: "Your AIOS dashboard is the frontend; the email-reading scripts are the backend.",
      teacher: "Frontend is the dining room; backend is the kitchen." },
    { n: 12, type: "AI Basic Knowledge 101", source: "Basics · Web", title: "12 · Server / Client",
      summary: "The client asks (your phone or browser); the server answers (a computer, usually in the cloud).",
      why: "Almost everything online is a client talking to a server.",
      teacher: "You (client) phone the shop (server) and ask them to do something." },
    { n: 13, type: "AI Basic Knowledge 101", source: "Basics · Web", title: "13 · Cloud / Serverless",
      summary: "Cloud = renting computers over the internet instead of owning them. Serverless = you just upload code that runs on demand; the provider handles the machines.",
      why: "Your dashboard is hosted free on GitHub's cloud.",
      teacher: "Cloud is renting a car instead of buying one; serverless is just paying per ride." },
    { n: 14, type: "AI Basic Knowledge 101", source: "Basics · Web", title: "14 · Open source",
      summary: "Code that anyone can see, use, and change, usually for free.",
      why: "Many AI models and tools are open source, so you can run or modify them yourself.",
      teacher: "A recipe printed in a free cookbook — anyone can cook it or tweak it." },
    { n: 15, type: "AI Basic Knowledge 101", source: "Basics · Web", title: "15 · Repository (repo) / Git / GitHub",
      summary: "A repo is a project folder of code. Git records every change (the history). GitHub is a website that stores repos online.",
      why: "Your AIOS dashboard lives in a GitHub repo.",
      teacher: "Git is the \"track changes\" of code; GitHub is the shared drive that holds it." },

    /* ---- B. How AI models actually work ---- */
    { n: 16, type: "AI Basic Knowledge 101", source: "Basics · AI core", title: "16 · AI — Artificial Intelligence",
      summary: "Software that does tasks we used to think needed human thinking: understanding language, recognising images, making decisions.",
      why: "The umbrella word for everything in this list.",
      teacher: "A machine doing \"smart\" jobs — not magic, just very good pattern-matching." },
    { n: 17, type: "AI Basic Knowledge 101", source: "Basics · AI core", title: "17 · Machine Learning (ML)",
      summary: "Teaching a computer by showing it many examples, so it learns the patterns itself — instead of a human writing exact rules.",
      why: "It's the method behind almost all modern AI.",
      teacher: "You don't define \"cat\" in words; you show 10,000 cat photos and it figures out what a cat looks like." },
    { n: 18, type: "AI Basic Knowledge 101", source: "Basics · AI core", title: "18 · Deep Learning / Neural Network",
      summary: "A neural network is a web of simple math units loosely inspired by brain cells. Deep learning stacks many layers of them, which powers today's strongest AI.",
      why: "LLMs are large neural networks.",
      teacher: "Layers of tiny decision-makers, each passing a hint to the next, until the whole stack \"gets it\"." },
    { n: 19, type: "AI Basic Knowledge 101", source: "Basics · AI core", title: "19 · Model",
      summary: "The trained \"brain\" file that makes predictions. \"GPT-5\" and \"Claude\" are models.",
      why: "When you \"choose a model\", you're choosing which brain answers you.",
      teacher: "A model is the graduate after all the studying — the finished, ready-to-work brain." },
    { n: 20, type: "AI Basic Knowledge 101", source: "Basics · AI core", title: "20 · LLM — Large Language Model",
      summary: "A model trained on huge amounts of text that works by predicting the next words. It can chat, write, summarise, translate, and code.",
      why: "ChatGPT, Claude, Gemini are all LLMs.",
      teacher: "An extremely well-read auto-complete that finishes your thought in a useful way." },
    { n: 21, type: "AI Basic Knowledge 101", source: "Basics · AI core", title: "21 · Training vs Inference",
      summary: "Training = the slow, expensive process of teaching a model from data (done once, by big labs). Inference = actually USING the trained model to get an answer (fast, every time you ask).",
      why: "You pay for inference each time you use AI; training is what the lab already did.",
      teacher: "Training is years of school; inference is answering a question on the spot." },
    { n: 22, type: "AI Basic Knowledge 101", source: "Basics · AI core", title: "22 · Parameters / Weights",
      summary: "The millions or billions of numbers inside a model that store what it learned. \"70B parameters\" means 70 billion of them.",
      why: "More parameters can mean a smarter (but heavier, costlier) model.",
      teacher: "Like the strength of every connection in a brain — together they hold all the knowledge." },
    { n: 23, type: "AI Basic Knowledge 101", source: "Basics · AI core", title: "23 · GPU",
      summary: "A special computer chip that is very fast at the heavy math AI needs. AI runs far faster on GPUs than on normal CPUs.",
      why: "GPU shortages and cost are a big reason AI is expensive.",
      teacher: "A CPU is a few brilliant workers; a GPU is thousands of simple workers doing the same sum at once." },
    { n: 24, type: "AI Basic Knowledge 101", source: "Basics · AI core", title: "24 · Transformer",
      summary: "The model design (invented 2017) behind GPT and Claude. Its trick is \"attention\": focusing on the most relevant words when deciding what comes next.",
      why: "The \"T\" in GPT stands for Transformer.",
      teacher: "When reading a sentence, it knows which earlier words matter most for the next one." },
    { n: 25, type: "AI Basic Knowledge 101", source: "Basics · AI core", title: "25 · Token",
      summary: "A small chunk of text, roughly ¾ of a word. Models read text and charge money by the token. \"Hello world\" is about 2 tokens.",
      why: "Your cost and the size limits are all measured in tokens.",
      teacher: "Tokens are the AI's syllables — it reads and bills by them, not by whole words." },
    { n: 26, type: "AI Basic Knowledge 101", source: "Basics · AI core", title: "26 · Context window",
      summary: "How much text (in tokens) a model can \"hold in mind\" at once. A bigger window means it can read more before answering.",
      why: "If a document is bigger than the window, the model can't see all of it.",
      teacher: "The size of the desk: only what fits on the desk can be looked at while working." },
    { n: 27, type: "AI Basic Knowledge 101", source: "Basics · AI core", title: "27 · Prompt / Prompt engineering",
      summary: "A prompt is the instruction or question you give the AI. Prompt engineering is the skill of wording it well to get a better answer.",
      why: "The same model gives much better results with a clearer prompt — a key thing to teach.",
      teacher: "Ask a vague question, get a vague answer; ask precisely, get gold." },
    { n: 28, type: "AI Basic Knowledge 101", source: "Basics · AI core", title: "28 · System prompt",
      summary: "Hidden instructions that set the AI's role and rules before your conversation starts (e.g. \"You are a polite tutor\").",
      why: "It shapes the AI's behaviour for the whole chat.",
      teacher: "The director's note to an actor before the scene begins." },
    { n: 29, type: "AI Basic Knowledge 101", source: "Basics · AI core", title: "29 · Temperature",
      summary: "A setting for creativity/randomness. Low temperature = focused and repeatable; high temperature = more creative and varied.",
      why: "Use low for facts and code, higher for brainstorming.",
      teacher: "A dial between \"careful accountant\" and \"wild poet\"." },
    { n: 30, type: "AI Basic Knowledge 101", source: "Basics · AI core", title: "30 · Hallucination",
      summary: "When an AI states something false but sounds completely confident.",
      why: "This is why you must always check important AI answers.",
      teacher: "A student who never says \"I don't know\" — they just make something up that sounds right." },
    { n: 31, type: "AI Basic Knowledge 101", source: "Basics · AI core", title: "31 · Multimodal",
      summary: "A model that handles more than text — also images, audio, or video.",
      why: "Lets you show the AI a photo or speak to it, not just type.",
      teacher: "Not just a reader — also eyes and ears." },
    { n: 32, type: "AI Basic Knowledge 101", source: "Basics · AI core", title: "32 · Foundation / Frontier / Open-weight model",
      summary: "Foundation model = a big general model others build on. Frontier model = the newest, most capable. Open-weight model = one whose trained weights are released so you can run it yourself (e.g. Llama, Qwen).",
      why: "Helps you compare \"closed\" services (GPT, Claude) vs models you can host.",
      teacher: "Frontier = the latest flagship phone; open-weight = a phone you're allowed to open and modify." },

    /* ---- C. Customising & connecting AI ---- */
    { n: 33, type: "AI Basic Knowledge 101", source: "Basics · Building", title: "33 · Fine-tuning",
      summary: "Extra-training a base model on your own examples so it specialises — for example, to match your company's tone or task.",
      why: "A way to make a general model behave like a specialist.",
      teacher: "A skilled chef taking a short course to master one specific cuisine." },
    { n: 34, type: "AI Basic Knowledge 101", source: "Basics · Building", title: "34 · Embedding",
      summary: "Turning a piece of text into a list of numbers that captures its meaning, so a computer can measure how similar two texts are.",
      why: "It's how \"search by meaning\" works.",
      teacher: "Giving every sentence map-coordinates, so related ideas sit close together." },
    { n: 35, type: "AI Basic Knowledge 101", source: "Basics · Building", title: "35 · Vector / Vector database",
      summary: "A vector is that list of numbers (an embedding). A vector database stores them so you can search by meaning instead of exact words.",
      why: "The storage behind \"chat with your documents\".",
      teacher: "A library organised by what books are ABOUT, not by their title spelling." },
    { n: 36, type: "AI Basic Knowledge 101", source: "Basics · Building", title: "36 · RAG — Retrieval-Augmented Generation",
      summary: "Give the AI your own documents to look up FIRST, then let it answer using those facts — instead of relying only on its memory.",
      why: "How you make AI answer about YOUR data accurately.",
      teacher: "Open-book exam: the AI checks your notes before answering, so it doesn't guess." },
    { n: 37, type: "AI Basic Knowledge 101", source: "Basics · Building", title: "37 · Tool / Function calling",
      summary: "Letting the AI trigger real actions — search the web, send an email, run code — by \"calling tools\", not just chatting.",
      why: "This is what turns a chatbot into something that gets things done.",
      teacher: "Giving the AI hands, not just a mouth." },
    { n: 38, type: "AI Basic Knowledge 101", source: "Basics · Building", title: "38 · MCP — Model Context Protocol",
      summary: "A shared standard so AI assistants can plug into tools and data sources the same way everywhere, instead of a custom connector for each.",
      why: "Increasingly how AI apps connect to your files, Gmail, calendars, etc.",
      teacher: "A USB-C port for AI: one standard plug that fits many devices." },
    { n: 39, type: "AI Basic Knowledge 101", source: "Basics · Building", title: "39 · API key / Token (auth)",
      summary: "A secret password-like string that proves it's you when calling a paid AI service. Keep it private — anyone with it can spend your money.",
      why: "You'll create and paste these to use most AI APIs.",
      teacher: "The key to your account — never post it in public code." },
    { n: 40, type: "AI Basic Knowledge 101", source: "Basics · Building", title: "40 · Rate limit / Quota / Credits",
      summary: "A cap on how many requests (or tokens) you may use in a time window, or how much credit you've paid for.",
      why: "Hitting the limit pauses your app until it resets.",
      teacher: "A speed limit + a fuel tank: only so fast, and only so far per fill-up." },

    /* ---- D. Agents & using AI for real work ---- */
    { n: 41, type: "AI Basic Knowledge 101", source: "Basics · Agents", title: "41 · AI Agent",
      summary: "An AI that doesn't just answer once, but plans steps, uses tools, checks its work, and keeps going toward a goal on its own.",
      why: "The big 2026 shift: from chatbots to agents that DO tasks.",
      teacher: "A chatbot answers a question; an agent goes and finishes the whole job." },
    { n: 42, type: "AI Basic Knowledge 101", source: "Basics · Agents", title: "42 · Agentic",
      summary: "A word describing AI that acts and decides over multiple steps, rather than giving one-shot replies.",
      why: "You'll hear \"agentic workflow\" everywhere now.",
      teacher: "\"Agentic\" = behaving like a do-er, not just a talker." },
    { n: 43, type: "AI Basic Knowledge 101", source: "Basics · Agents", title: "43 · Copilot / Assistant",
      summary: "An AI that helps you do a task (write code, draft an email) while you stay in control and approve the work.",
      why: "The friendliest, lowest-risk way to use AI at work.",
      teacher: "A co-pilot helps fly the plane — you're still the captain." },
    { n: 44, type: "AI Basic Knowledge 101", source: "Basics · Agents", title: "44 · Orchestration",
      summary: "Coordinating several models, tools, or steps together to complete a bigger job.",
      why: "Real AI products are usually many small steps wired together.",
      teacher: "A conductor making many musicians play one piece in time." },
    { n: 45, type: "AI Basic Knowledge 101", source: "Basics · Agents", title: "45 · Guardrails",
      summary: "Rules and filters that keep an AI safe and on-policy — blocking bad output or limiting what actions it may take.",
      why: "Essential before letting AI touch real systems or talk to customers.",
      teacher: "The fence at the edge of a cliff path — freedom to walk, protection from falling." },
    { n: 46, type: "AI Basic Knowledge 101", source: "Basics · Agents", title: "46 · Sandbox",
      summary: "A safe, walled-off space where AI or code can run without touching your real files or system.",
      why: "Lets agents try risky actions safely.",
      teacher: "A children's sandbox: play and make a mess, but it stays contained." },
    { n: 47, type: "AI Basic Knowledge 101", source: "Basics · Agents", title: "47 · Evals (Evaluation)",
      summary: "Repeatable tests that measure whether an AI's output is good or correct, so you can improve it on purpose instead of by guessing.",
      why: "How serious teams know if a change made the AI better or worse.",
      teacher: "Exams for the AI — score it the same way each time to see real progress." },
    { n: 48, type: "AI Basic Knowledge 101", source: "Basics · Agents", title: "48 · Latency & Cost (per-token pricing)",
      summary: "Latency = the delay between asking and getting an answer. Cost = you usually pay by tokens in + tokens out, so longer prompts and answers cost more.",
      why: "The two things you constantly balance when building with AI: speed and money.",
      teacher: "Like a taxi: you feel the wait (latency) and you pay by distance (tokens)." }
  ]
};
