/* =============================================================================
   DASHBOARD_DATA  —  AUTO-GENERATED by tools/refresh.py
   Do not edit by hand; overwritten every refresh. Latest edition only.
   Source: OCC AI Opportunity Radar emails (myaiagent2026@gmail.com) via IMAP.
============================================================================= */
window.DASHBOARD_DATA = {
  "meta": {
    "brand": "AIOS",
    "tagline": "OCC AI OPPORTUNITY RADAR",
    "operator": "GARETT",
    "generatedAt": "2026-06-02 · 15:10 GMT+8",
    "latestBrief": "2026-06-02 · 15:10 GMT+8",
    "fetchedAt": "2026-06-02 19:25",
    "source": "myaiagent2026@gmail.com"
  },
  "briefs": [
    {
      "id": "trend",
      "title": "AI Trends & Maker Awareness",
      "accent": "cyan",
      "subtitle": "English-first market brief for Garett. Focus: AI-native builders, vibe coding, 3D/design workflows, local agents, creator automation, and practical teaching signals.",
      "date": "2026-06-02 · 15:10 GMT+8",
      "quickRead": [
        "OpenAI moving Codex into AWS is a strong sign that coding agents are becoming enterprise infrastructure.",
        "NVIDIA is pushing local and edge agents hard: Jetson, DGX Spark, NemoClaw, and open physical AI models.",
        "3D creation is moving from single asset generation into connected workflows: website showcases, classroom visuals, CNC, and physical making.",
        "HN maker signals point to compute efficiency and deep AI literacy becoming competitive advantages for small teams."
      ],
      "callout": {
        "label": "Market signal to watch",
        "text": "The big shift is not only better models. It is AI workflows becoming deployable infrastructure: agents on AWS, local workstations, edge devices, classrooms, creator websites, and physical fabrication loops. Garett should watch how these systems become teachable repeatable workflows, because that is where consulting value can compound."
      },
      "signals": [
        {
          "n": 1,
          "category": "Platform shift",
          "title": "OpenAI frontier models and Codex are now generally available on AWS Source type: Official",
          "source": "",
          "relevance": "Intermediate",
          "summary": "OpenAI says frontier models and Codex are now available through AWS, including Codex on Amazon Bedrock, so enterprises can use OpenAI inside existing security, procurement, billing, and governance workflows.",
          "why": "This is the market moving from AI demos to governed deployment. For teaching and consulting, the opportunity is to explain how agentic coding fits into real production constraints, not only how to prompt a tool.",
          "action": "Watch for AWS Bedrock examples that combine coding agents with security review, app modernization, and private repos.",
          "teacher": "Bedrock is AWS's managed AI platform. The signal is that companies can buy and govern Codex through a platform they already trust, which lowers adoption friction.",
          "link": "https://openai.com/index/openai-frontier-models-and-codex-are-now-available-on-aws/"
        },
        {
          "n": 2,
          "category": "Edge agents",
          "title": "NVIDIA JetPack 7.2 makes Jetson more agent-ready Source type: Official",
          "source": "",
          "relevance": "Advanced",
          "summary": "NVIDIA says JetPack 7.2 supports one-command deployment of NemoClaw on Jetson and introduces Jetson agent skills for device-side and board-support workflows. The update also adds memory and workload improvements for edge AI.",
          "why": "AI assistants are moving from laptops and browsers into cameras, robots, kiosks, and physical installations. This is relevant to any future consulting around local creative automation or AI-enabled exhibits.",
          "action": "Track small Jetson demos that run vision agents locally, especially ones that combine camera input with task automation.",
          "teacher": "Edge AI means running AI close to the sensor or device instead of only in the cloud. Agent skills are reusable instructions that tell an agent how to perform and verify a task.",
          "link": "https://developer.nvidia.com/blog/deploy-agentic-ready-ai-at-the-edge-with-memory-efficiency-in-nvidia-jetpack-7-2/"
        },
        {
          "n": 3,
          "category": "Local agents",
          "title": "NVIDIA DGX Spark targets long-running local AI agents Source type: Official",
          "source": "",
          "relevance": "Advanced",
          "summary": "NVIDIA describes DGX Spark updates for running autonomous local agents with NemoClaw, Qwen3.6, OpenClaw-style harnesses, secure sandboxes, and guided multi-node clustering.",
          "why": "Local agents are becoming a product category. The consulting angle is privacy, predictable cost, and creative pipelines that can run without sending every asset or client file to the cloud.",
          "action": "Compare cloud-agent workflows with local-agent workflows for file-heavy design or 3D projects.",
          "teacher": "A local agent runs on your own machine. The main tradeoff is hardware cost versus privacy, control, and no per-token cloud billing for local inference.",
          "link": "https://developer.nvidia.com/blog/run-local-ai-agents-with-faster-models-and-multi-node-clustering-on-nvidia-dgx-spark/"
        },
        {
          "n": 4,
          "category": "Physical AI and 3D",
          "title": "NVIDIA Cosmos 3 unifies reasoning, world generation, and action models Source type: Official",
          "source": "",
          "relevance": "Advanced",
          "summary": "NVIDIA says Cosmos 3 is an open foundation model for physical AI, with Nano and Super checkpoints, code, datasets, post-training scripts, and deployment tools. It combines a reasoning tower with a diffusion generator for world and action generation.",
          "why": "The 3D and CG market is drifting toward world models that understand motion, scene physics, and actions. That affects how creators will storyboard, simulate, and teach spatial workflows.",
          "action": "Watch for demos that turn static 3D scenes into controllable video or robotics-style simulations.",
          "teacher": "A world model tries to predict how a scene changes over time. Physical AI applies that to robots, vehicles, smart spaces, or simulated environments.",
          "link": "https://developer.nvidia.com/blog/develop-physical-ai-reasoning-world-and-action-models-with-nvidia-cosmos-3/"
        },
        {
          "n": 5,
          "category": "Hacker News signal",
          "title": "Launch HN: Expanse uses AI to unlock wasted GPU cluster capacity Source type: Hacker News",
          "source": "",
          "relevance": "Advanced",
          "summary": "The Expanse team says datacenters often run at only 30% to 40% effective utilization because users over-request GPU and HPC resources. Their tool predicts resource needs, flags likely failures, and gives line-level optimization suggestions before jobs run.",
          "why": "Compute literacy is becoming part of AI literacy. Teachers and consultants who can explain cost, VRAM, batching, and utilization will be more useful than people who only teach prompts.",
          "action": "Add a simple compute-cost lesson to future AI workshops: why over-requesting GPUs wastes money and how profiling helps.",
          "teacher": "HPC means high-performance computing. SLURM and Kubernetes are schedulers that decide where jobs run. The signal is that AI can optimize infrastructure before humans waste expensive GPUs.",
          "link": "https://news.ycombinator.com/item?id=48356312"
        },
        {
          "n": 6,
          "category": "AI education",
          "title": "Stanford CS336 puts language-model building into a from-scratch curriculum Source type: Hacker News",
          "source": "",
          "relevance": "Intermediate",
          "summary": "Stanford's CS336 course walks students through building language models from data collection and tokenizer implementation to training, scaling, alignment, and deployment. It was actively discussed on Hacker News today.",
          "why": "The education market is splitting between easy prompting and deep builder literacy. Garett can position teaching around practical intuition without needing every student to become a model researcher.",
          "action": "Skim the assignment list and convert it into a non-technical lesson map: data, model, training, evaluation, alignment.",
          "teacher": "From-scratch does not mean no tools. It means students implement the core pieces themselves so they understand what the tools hide.",
          "link": "https://news.ycombinator.com/item?id=48357075"
        },
        {
          "n": 7,
          "category": "3D creator workflow",
          "title": "Tripo and Readdy show a character-to-website workflow for indie creators Source type: Official",
          "source": "",
          "relevance": "Beginner",
          "summary": "Tripo describes a workflow where a creator generates a game character as a GLB asset, then uses Readdy to build an interactive web showcase around it. The example turns a Forest Guardian concept into a live presentation page.",
          "why": "This is a practical creator-client signal: the deliverable is no longer only an image or model, but a fast interactive pitch page. That is teachable and immediately useful for students or clients.",
          "action": "Test one mini workflow: image prompt to GLB, then embed that asset into a simple landing page.",
          "teacher": "GLB is a web-friendly 3D file format. It lets viewers rotate and inspect a model in a browser without installing 3D software.",
          "link": "https://www.tripo3d.ai/blog/tripo-readdy-character-to-website"
        },
        {
          "n": 8,
          "category": "Digital to physical",
          "title": "Tripo, Makerables, and Makera point to AI 3D moving into physical fabrication Source type: Official",
          "source": "",
          "relevance": "Intermediate",
          "summary": "Tripo describes a workflow where image or prompt generated 3D models move into community sharing, remixing, relief generation, and desktop CNC production through Makerables and Makera.",
          "why": "Maker workflows are becoming content, product, and teaching workflows at the same time. This could support consulting around rapid prototyping, retail props, collectible concepts, or class demos.",
          "action": "Watch whether AI 3D tools start exporting more fabrication-ready files, not just pretty preview models.",
          "teacher": "CNC means computer numerical control. A CNC machine cuts or engraves real material from a digital file, so AI assets can become physical objects.",
          "link": "https://www.tripo3d.ai/blog/tripo-makera-ai-3d-creation-workflow"
        },
        {
          "n": 9,
          "category": "Teaching workflow",
          "title": "Tripo and YouMind turn flat diagrams into 3D teaching material Source type: Official",
          "source": "",
          "relevance": "Beginner",
          "summary": "Tripo's blog list describes a geography-teacher workflow using YouMind and Tripo to convert abstract geology diagrams into interactive 3D models, reducing PPT creation time from 3 hours to 10 minutes in the case study.",
          "why": "This directly matches the long-term teaching/consulting direction. The valuable skill is building simple visual explanations that make abstract content concrete.",
          "action": "Pick one boring 2D slide and test whether AI 3D can make it easier to teach in under 15 minutes.",
          "teacher": "Interactive 3D is powerful for education because learners can rotate, inspect, and spatially understand a concept instead of only seeing a fixed diagram.",
          "link": "https://www.tripo3d.ai/blog/tripo-youmind-flat-diagrams-to-3d-models"
        },
        {
          "n": 10,
          "category": "Mobile capture to AI 3D",
          "title": "Tripo and KIRI Engine show AI 3D extending mobile scans Source type: Official",
          "source": "",
          "relevance": "Intermediate",
          "summary": "Tripo's blog list describes using AI 3D generation with mobile 3D scans to restyle real objects, create lighter assets, and build mixed real-and-AI 3D scenes.",
          "why": "This is a realistic bridge for designers: scan a real product or prop, then use AI to stylize, simplify, or extend it. That can speed up client mockups and visual development.",
          "action": "Test a phone scan of a small object and compare the raw scan, AI-restyled version, and optimized game-ready version.",
          "teacher": "Photogrammetry or mobile 3D scanning captures real objects. AI 3D can then turn that capture into a cleaner, lighter, or more stylized model.",
          "link": "https://www.tripo3d.ai/blog/tripo-kiriengine-mobile-3d-scans"
        }
      ]
    },
    {
      "id": "job",
      "title": "AI Life & Job Opportunity",
      "accent": "green",
      "subtitle": "English-first brief for Garett - Tuesday, June 2, 2026, 15:00 GMT+8",
      "date": "2026-06-02 · 15:00 GMT+8",
      "quickRead": [
        "Design work is moving from single prompts into reusable agent skills: Figma, UX linting, slide decks, and visual assets can now be systematized.",
        "The best consulting angle is not 'AI tools training'. It is workflow productization: audit, standardize, automate, and verify creative operations.",
        "Several new tools are weak products but strong signals: clients will ask for agent dashboards, AI report generation, and AI-native marketing analytics.",
        "Garett can convert these into teaching modules: AI design QA, client report automation, course slide generation, and agent-managed production pipelines."
      ],
      "callout": {
        "label": "Best move for Garett today",
        "text": "Build one small 'AI Design QA' demo: take a messy Figma or web layout, run it through a token check, accessibility check, anti-slop UX critique, and final human art-director review. This can become a class exercise, a consulting diagnostic, and a paid client audit offer."
      },
      "signals": [
        {
          "n": 1,
          "category": "Design systems",
          "title": "Figma Console MCP Skills turn design-system work into reusable agent playbooks",
          "source": "GitHub",
          "relevance": "Advanced",
          "summary": "The repo repackages Figma Console MCP capabilities as Markdown skills for the native Figma MCP server. It covers token export/import, variables, component analysis, WCAG linting, accessibility audits, version diffing, comments, FigJam, and Slides.",
          "why": "This is a clear teaching and consulting product: 'turn your Figma chaos into a verified design system workflow.' Garett can sell audits, token cleanup, accessibility checks, and team training around agent-assisted Figma operations.",
          "action": "Test one Figma file by asking an agent to extract tokens, list components, and produce a before-after design-system audit checklist.",
          "teacher": "MCP means Model Context Protocol. It lets an AI assistant connect to a tool, such as Figma, through structured commands instead of screenshots and guesses. WCAG is the accessibility rulebook used to check contrast, readability, and interface usability.",
          "link": "https://github.com/southleft/figma-console-mcp-skills"
        },
        {
          "n": 2,
          "category": "UX quality",
          "title": "ux-skill adds a multi-IDE anti-AI-slop UX linter for coding agents",
          "source": "GitHub",
          "relevance": "Intermediate",
          "summary": "ux-skill describes a design intelligence engine with brand specs, palettes, type pairings, component guidance, UX laws, anti-pattern rules, slash commands, sub-agents, and MCP tools. It says it works across Claude Code, Cursor, Windsurf, Copilot, Gemini CLI, Codex, and other IDEs.",
          "why": "Vibe coding will produce lots of ugly client-facing apps. Garett can teach students how to judge and repair AI-generated interfaces, then package that as a 'senior art director review for AI apps' consulting offer.",
          "action": "Run it against a simple AI-built landing page and compare the linter output with Garett's own manual visual critique.",
          "teacher": "An anti-pattern is a common bad solution that looks useful but causes problems. 'AI slop' means generic AI output that is technically present but visually weak, inconsistent, or unsuitable for a real client.",
          "link": "https://github.com/Laith0003/ux-skill"
        },
        {
          "n": 3,
          "category": "Strategy consulting",
          "title": "BeeVibe CTO frames AI as a decision layer for architecture and strategy",
          "source": "GitHub",
          "relevance": "Advanced",
          "summary": "BeeVibe CTO describes itself as 'the decision layer your coding agents are missing' and focuses on architecture deep research for strategic system design decisions. The repo positions AI less as a coder and more as a structured adviser for tradeoffs.",
          "why": "This is a good model for Garett's future consulting: not just making images, but helping studios choose pipelines, tools, proof standards, and adoption roadmaps. Senior judgment becomes the product.",
          "action": "Draft a one-page 'AI pipeline decision memo' for a small studio choosing between ComfyUI, cloud image tools, and local workstation workflows.",
          "teacher": "A decision layer is the part of a workflow that compares options, risks, costs, and constraints before production begins. In consulting, this is often more valuable than the final tool button-clicking.",
          "link": "https://github.com/beevibe-ai/beevibe-cto"
        },
        {
          "n": 4,
          "category": "Client reporting",
          "title": "Fluxito turns marketing analytics, tags, dashboards, and reports into an AI-operated workflow",
          "source": "GitHub",
          "relevance": "Advanced",
          "summary": "Fluxito is an open-source MCP server and web platform for marketing analytics. It says it can help define tracking plans, implement Google Tag Manager and Adobe Launch work, read GA4 and ad platforms, build dashboards, and automate reporting through an MCP-compatible AI.",
          "why": "Client reports are often where freelancers lose time. Garett can turn this into an 'AI client reporting system' offer for studios: campaign tracking, dashboard sanity checks, and weekly visual summaries.",
          "action": "Map one client-report template into sections: goals, assets delivered, traffic signals, conversion signals, visual next steps, and risks.",
          "teacher": "GA4 is Google Analytics 4. GTM is Google Tag Manager. A tracking plan defines which user actions are measured, such as clicks, form submissions, downloads, or purchases.",
          "link": "https://github.com/digitalXperiments/fluxito"
        },
        {
          "n": 5,
          "category": "Self-hosted assistants",
          "title": "Open-source Genspark-style agent workspace targets reports, slides, sheets, images, and task execution",
          "source": "GitHub",
          "relevance": "Advanced",
          "summary": "The repo describes a self-hosted Super Agent framework inspired by Genspark, with multi-model orchestration, 80+ tools, web search, code execution, file I/O, image and video generation, document creation, slide decks, spreadsheets, and reports. It emphasizes local/self-hosted deployment and model choice.",
          "why": "This signals that clients will soon expect custom 'studio assistants' rather than one-off ChatGPT sessions. Garett can teach how to scope a safe assistant: research, draft, render, check, report, and hand off to a human.",
          "action": "Create a paper prototype for a '3D course support agent' that answers lesson questions, generates exercises, and prepares weekly recap PDFs.",
          "teacher": "Self-hosted means the software can run on your own machine or server instead of only inside a vendor's cloud. Multi-model orchestration means one task can be split across several AI models or agents.",
          "link": "https://github.com/veryyoldman/Genspark-AI"
        },
        {
          "n": 6,
          "category": "Course decks",
          "title": "Beamer Academic converts papers into structured academic slide decks for Claude Code and Codex",
          "source": "GitHub",
          "relevance": "Intermediate",
          "summary": "Beamer Academic says it turns a thesis, PDF, Word file, or LaTeX source into professional Beamer defense slides through extraction, outline, content generation, and PDF output. It lists 13 layouts, color schemes, and examples with architecture diagrams and formulas.",
          "why": "The same pattern can upgrade course creation: source notes in, structured lecture deck out, then Garett does the art direction and examples. This is a direct speed boost for teaching.",
          "action": "Feed one technical article about 3D lighting or AI rendering into a slide workflow and evaluate whether the outline teaches the topic correctly.",
          "teacher": "Beamer is a LaTeX system for making academic presentation slides. It is strong for formulas, diagrams, and structured research talks, but normally requires technical formatting knowledge.",
          "link": "https://github.com/Faust-Donf/beamer-academic"
        },
        {
          "n": 7,
          "category": "Creator assets",
          "title": "huashu-slide-codex packages slides, covers, and thumbnails as a Codex-only visual production skill",
          "source": "GitHub",
          "relevance": "Intermediate",
          "summary": "The repo describes a Codex-only skill that creates PPTX decks, HTML decks, editable HTML-to-PPTX decks, and single cover images for articles or video thumbnails. It emphasizes brand asset preparation, multiple design philosophies, and built-in image generation.",
          "why": "This is directly useful for course thumbnails, YouTube covers, workshop decks, and client proposal visuals. Garett can turn the workflow into a content-production class for artists who hate starting from blank slides.",
          "action": "Make three cover directions for a lesson called 'AI Lighting Workflow for Product Renders' and judge them against typography, hierarchy, and brand fit.",
          "teacher": "A skill is a reusable instruction package for an AI agent. Instead of prompting from scratch every time, the skill defines the process, outputs, quality checks, and files to produce.",
          "link": "https://github.com/alchaincyf/huashu-slide-codex"
        },
        {
          "n": 8,
          "category": "Agent operations",
          "title": "Glink Engine uses YAML, a JSONL blackboard, checkpoints, and dashboards for multi-agent workflows",
          "source": "GitHub",
          "relevance": "Advanced",
          "summary": "Glink is a lightweight orchestration engine that routes workflow steps to agents, passes context, handles failures, logs to a shared JSONL blackboard, resumes from checkpoints, and exposes a dashboard and HTTP/SSE status stream.",
          "why": "This is the workflow pattern behind serious AI services: briefing, research, creation, QA, delivery, and logs. Garett can sell an 'AI production command center' setup for small creative teams.",
          "action": "Sketch a YAML workflow for a 3D client report: gather inputs, draft summary, generate visuals, review quality, export PDF, send to client.",
          "teacher": "YAML is a readable configuration format. JSONL is one JSON record per line, useful for logs. Checkpointing means the workflow can restart after a failure without repeating every step.",
          "link": "https://github.com/garyqlin/glink-engine"
        },
        {
          "n": 9,
          "category": "QA and verification",
          "title": "Review Forge turns code review into an auditable multi-pass agent workflow",
          "source": "GitHub",
          "relevance": "Intermediate",
          "summary": "Review Forge is an Agent Skill for structured code review. It supports multi-pass LLM review, synthesis, human-approved fix selection, implementation, regression testing, independent verification, and status tracking under a code_review folder.",
          "why": "The important idea is not only code. It is proof. Garett can adapt this pattern for visual deliverables: review, synthesize, approve fixes, apply only approved fixes, verify, and document status.",
          "action": "Create a visual Review Forge checklist for renders: composition, product accuracy, typography, lighting, material, client brief match, and delivery format.",
          "teacher": "Regression testing means checking that a fix did not break something that used to work. In creative work, the equivalent is making sure a corrected render still matches the original brief and does not introduce new mistakes.",
          "link": "https://github.com/vikingmute/review-forge"
        },
        {
          "n": 10,
          "category": "Multimodal tool access",
          "title": "Model Studio CLI exposes Qwen chat, image, video, speech, search, memory, and workflows as structured agent tools",
          "source": "GitHub",
          "relevance": "Advanced",
          "summary": "The official Model Studio CLI for Aliyun Model Studio says agents can call text chat, multimodal understanding, image generation/editing, video generation/editing, speech, OCR, memory, knowledge bases, app workflows, and web search through structured tool calls.",
          "why": "Multimodal toolchains are becoming one command-line layer, not separate apps. Garett can teach how to choose the right model family for image, video, voice, report, or coding tasks and how to protect quality with human checkpoints.",
          "action": "Design a comparison table for class: one row each for image generation, image editing, video edit, OCR, speech, and memory, with quality risks and best-use cases.",
          "teacher": "Multimodal means the AI can handle more than text, such as images, audio, video, and documents. Structured tool calls mean the AI requests a tool with defined inputs instead of typing vague instructions.",
          "link": "https://github.com/modelstudioai/cli"
        }
      ]
    }
  ]
};
